language: python

sudo: required

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
    - "nightly"

matrix:
    allow_failures:
      - python: "pypy3"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
    - docker pull progrium/consul
    - docker run -d -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap

install:
    - make requirements
    - pip install coveralls

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then make isort-check; fi
    - make test

after_success:
    - coveralls

services:
    - redis
    - docker

deploy:
  provider: pypi
  user: drgarcia1986
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: drgarcia1986/simple-settings
  skip_cleanup: true
